### ISSUE TITLE
Find a map-based dataset

### ISSUE THREAD

**Issue by xordspar0** [marckostelecky/DataViz#5]
We probably want to get one from www.data.gov.

**Comment by FlaminHotCheeto** [comment]
What do you guys think of this one? http://catalog.data.gov/dataset/alternative-fueling-station-locations-b550c/resource/61b4f02f-2f54-47c8-9270-0ef553aaa082

Trying to find one that doesn't have thousands of points and is somewhat evenly spread across the country.  The map view on that link shows distribution

**Comment by xordspar0** [comment]
Looks promising. Good find. Think about how we can display this dataset specifically. What could we add to our vizualization to make this data set meaningful?
Here's an idea: Let's say you have a hydrogen car. There are certain places you can't go since you'll run out of fuel before finding a refueling station. We could shade regions of the map that are safe/unsafe for each fuel type.
